spring.application.name=api-gateway

server.port=9090

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable service discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Routes
spring.cloud.gateway.server.webflux.routes[0].id=account-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/accounts/**

spring.cloud.gateway.server.webflux.routes[1].id=loanservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://LOANSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/loans/**